### ISSUE TITLE
CESM2/CESM2-WACC level to true altitude

### ISSUE THREAD

**Issue by Gabrielpfreitas** [NordicESMhub/NEGI-Abisko-2019#108]
Hej, 

I have a problem with both of these models.

I can't seem to translate the level (that is in negative hPa(-3 to -992)) to true altitude of the cells.

There's no equation in the files.

Do anybody knows how could I translate it?

Thanks in advance :)

Gabriel

**Comment by daliagachc** [comment]
@sarambl , @jgliss , @annefou ? 
I can work on it, but havent done it before. maybe you had?

**Comment by sarambl** [comment]
I think they just made it negative.

**Comment by sarambl** [comment]
Also, it might be in hybrid sigma coordinates

**Comment by sarambl** [comment]
http://www.cesm.ucar.edu/models/atm-cam/docs/usersguide/node25.html

**Comment by sarambl** [comment]
So, basically, there is a function depending on PS (surface pressure) and some coefficients that should also be in the data. After this you will have to interpolate to pressure. THEN you can calculate the altitude in km, but I would maybe just stick to the pressure coordinates.

**Comment by annefou** [comment]
Maybe https://nordicesmhub.github.io/GEO4962/06-vertical_interpolation/index.html can be helpful.

The easiest is probably to create a local conda environment for this (https://www.pyngl.ucar.edu/Download/).

**Comment by sarambl** [comment]
Actually, it's in atmosphere levels for CESM and WACCAM

**Comment by MichaelSchulzMETNO** [comment]
For CESM2-WACCM : The formula is in the netcdf attribute for the lev or lev-bnds variable
p = a*p0 + b*ps

**Comment by annefou** [comment]
@MichaelSchulzMETNO Ah yes! Thank you.

**Comment by sarambl** [comment]
THanks @MichaelSchulzMETNO , but the coefficients (a and b) are not to be seen?

**Comment by MichaelSchulzMETNO** [comment]
a and b depend on level only, small eternal files

**Comment by sarambl** [comment]
I know, but they should be listed?

**Comment by MichaelSchulzMETNO** [comment]
we need to download them from cmip6 repository, Gabriel indicated he has them

**Comment by sarambl** [comment]
I don't think that's true, he's sitting beside me

**Comment by MichaelSchulzMETNO** [comment]
ok lets search for them...

**Comment by sarambl** [comment]
I tried :smile: But you are a better (re)searcher than me

**Comment by MichaelSchulzMETNO** [comment]
I will start NOW

**Comment by sarambl** [comment]
I FOUND IT!

**Comment by MichaelSchulzMETNO** [comment]
argh - I go in pension...

**Comment by Gabrielpfreitas** [comment]
Hej all, we found it, thanks for the help :)

**Comment by MichaelSchulzMETNO** [comment]
worth to check for different vertical coordinates:

http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#vertical-coordinate

**Comment by Gabrielpfreitas** [comment]
Thanks! Will do!
