### ISSUE TITLE
pyaerocom regional trends

### ISSUE THREAD

**Issue by JohanRaniseth** [NordicESMhub/NEGI-Abisko-2019#114]
Hey @jgliss,

So pyaerocom has a nice .compute_trend/.trend commands for plotting trends for a specific station but is there something similar for regional trends?
I have filtered observation data for one region by using .filter_by_meta.

Also, if there is no easy regional trend command, is there any easy way of taking the mean over all stations for each timestep so the observation data is on the same form as for a specific station? And then use .compute_trend?

Link to notebook: 
https://abisko.uiogeo-apps.sigma2.no/user/73e7321f-a4b6-4010-9849-16003ed8f76b/lab/tree/Trend.ipynb

**Comment by jgliss** [comment]
@JohanRaniseth 

We haven't implemented the regional trends yet. I would do the following (some of which you have already done):

1. Filter the region that you are interested in (e.g. `UngriddedData.apply_filters`)
2. Retrieve timeseries for all stations and compute regional mean timeseries (as `pandas.Series` object)
3. Put the result from previous file into an empty `StationData` object and use the trends functionality

Does this sound feasible?

**Comment by jgliss** [comment]
@JohanRaniseth and @MichaelSchulzMETNO 

My colleague @augustinmortier just sent this example that shows how he computes regional timeseries using pyaerocom / EBAS. Maybe it helps:

```python
#read pm2.5 from EBAS
reader = pya.io.ReadUngridded('EBASMC')
obs_data = reader.read(vars_to_retrieve='concpm25')

#works only in EUROPE
region = 'EUROPE'

# subdata for selected region
f = pya.Filter(region)
sub = f(data)

#put all station_data in one dataframe df
data_all = sub.to_station_data_all()['stats']
df = pd.DataFrame()

for i, station in enumerate(data_all):
            stat_name = station.station_name
            ts_type = station.ts_type
            # set individual time series as dataframe

            # extract pandas series and convert it to datframe
            ts = data_all[i][var].to_frame()
            # remove duplicated index keeping the first occuence
            ts = ts.groupby(ts.index).first()
            #name the columns
            ts.set_axis([obs_var + '_' + stat_name], axis=1, inplace=True)

            # concatenates to main dataframe
            df = pd.concat([df, ts], axis=1)

#calculates median
med = df.median(axis=1)
#monthly average of that median
med_avg = med.resample('M').mean()
```
