### ISSUE TITLE
Hysplit data is only for 3 months

### ISSUE THREAD

**Issue by lassekva** [NordicESMhub/NEGI-Abisko-2019#122]
path: shared-ns1000k/inputs/hysplit_trajectories/zeppelin/HYSPLIT/

It's only data for three months, where can I get the rest? 

@jgliss , @ksenia-tabakova , @annefou

**Comment by ksenia-tabakova** [comment]
I see them in inputs,actually. Years 2017-2019, jan-mar.

**Comment by lassekva** [comment]
I understand why now.

**Comment by jgliss** [comment]
@lassekva @ksenia-tabakova 

Anything I need to do?
