### ISSUE TITLE
Problems exporting notebook to PDF.

### ISSUE THREAD

**Issue by JohanRaniseth** [NordicESMhub/NEGI-Abisko-2019#154]
I'm having problems exporting my notebook to PDF. I've loaded images into the notebook using html in the markdown cells but when I import it to PDF all the images disappear. Anyone know why or an easy way to fix it?

**Comment by annefou** [comment]
How did you proceed?
One easy way (not always very nice pdf) is to print it in pdf.

**Comment by JohanRaniseth** [comment]
I was using this html image loading/display(in markdown) when the notebook exporting created a PDF without images: 
<img src="subdirectory/MyImage.png"> 

Changed to this way of loading images(in code cell) which fixed the problem:
from IPython.display import Image
Image(filename='subdirectory/MyImage.png')
