### ISSUE TITLE
My server fails to launch?

### ISSUE THREAD

**Issue by sarambl** [NordicESMhub/NEGI-Abisko-2019#27]
![image](https://user-images.githubusercontent.com/17406708/67017592-4b759c80-f0fa-11e9-8465-d1cc9696e4ff.png)
@annefou ???? Iiik.

**Comment by annefou** [comment]
Yep! I gave too much resources to each notebook. I will reduced it but don't want to interrupt Jonas' presentation...
Try https://abisko2.uiogeo-apps.sigma2.no

**Comment by annefou** [comment]
hopefully fixed...
