### ISSUE TITLE
Read CMIP6 data into pyaerocom

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [NordicESMhub/NEGI-Abisko-2019#30]
Right now its not working, either read directly, or rename files...

**Comment by MichaelSchulzMETNO** [comment]
I did a test with Diego, and we copied a multiannual CMIP6 file into pyaerocom-testdata/modeldata and renamed the file to aerocom file name convention. And then a multiannual chunk was read correctly and could be plotted. So putting the file in place and renaming is enough to use pyaerocom for CMIP6 read....

**Comment by MichaelSchulzMETNO** [comment]
@jgliss Could we have an option in the modeldata read routine, where you give the file name directly?

**Comment by jgliss** [comment]
I added an example that shows how you can use pyaerocom with any modeldata (i.e. data that is not under pyaerocom-testdata/modeldata). You can find the example [here](https://github.com/NordicESMhub/NEGI-Abisko-2019/blob/master/content/training/pyaerocom/example_cmip6_colocation.ipynb).

I close this issue.
