### ISSUE TITLE
Where are slides from lectures?

### ISSUE THREAD

**Issue by ksenia-tabakova** [NordicESMhub/NEGI-Abisko-2019#33]
Hi! I am lost between all resources and simply can't locate slides.

**Comment by MichaelSchulzMETNO** [comment]
There are in a separate github repository open to the participants:
https://github.com/NordicESMhub/NEGI-Abisko-2019-private/tree/master/presentations

**Comment by ksenia-tabakova** [comment]
I don't seem to have access: it shows me: 404 page not found.

**Comment by annefou** [comment]
It should be done by now. Each student needs to accept invitation sent to be part of negi-students team.

**Comment by ksenia-tabakova** [comment]
I have accepted the invitation but link from Michael still is 404.

**Comment by MichaelSchulzMETNO** [comment]
start best here:

https://github.com/NordicESMhub/NEGI-Abisko-2019-private

**Comment by ksenia-tabakova** [comment]
And I did try this too but still it doesn't work. 
![Screenshot from 2019-10-17 21-08-45](https://user-images.githubusercontent.com/12828813/67039844-e8502e00-f12a-11e9-85d1-b8d939a04cca.png)

**Comment by MichaelSchulzMETNO** [comment]
Mille excuses, it seems you were not in the assistant team, Anne added you now...

**Comment by ksenia-tabakova** [comment]
No worries! Thanks, Anne, for adding me!
