### ISSUE TITLE
some .nc files from CMIP6 are empty

### ISSUE THREAD

**Issue by jrieksta** [NordicESMhub/NEGI-Abisko-2019#61]
@MichaelSchulzMETNO 
Hi! Some of my CMIP6 .nc files are empty. Is there something I can do?

**Comment by MichaelSchulzMETNO** [comment]
Go to another model, sorry
Michael

Jolanta Rieksta <notifications@github.com> schrieb am Fr. 18. Okt. 2019 um
15:04:

**Comment by MichaelSchulzMETNO** [comment]
Or try another esgf node

Jolanta Rieksta <notifications@github.com> schrieb am Fr. 18. Okt. 2019 um
15:04:

**Comment by annefou** [comment]
Or if I understood properly, you can check in shared-ns9034k-for-ns1000k where all CMIP6 original data should be too.

**Comment by sarambl** [comment]
Hey! I think that it might be worth it to try to download again. I had some issues with that but I just did it again.

**Comment by MichaelSchulzMETNO** [comment]
Is this issue closable

**Comment by sarambl** [comment]
Haha, well close it, @MichaelSchulzMETNO   :D
