### ISSUE TITLE
Help looking for data(CMIP6)

### ISSUE THREAD

**Issue by JohanRaniseth** [NordicESMhub/NEGI-Abisko-2019#68]
Hey,

We are looking for some model data. It would be the hist-piAer data from the IPSL-CM6A-LR model. 

Optionally: From the CANESM5 model: hist-piAer and od550(aerosol optical depth).

Also, does anyone know if Miroc6 is the same as Miroc-sprintars. I assume it is not the same..

**Comment by daliagachc** [comment]
@sarambl ?

**Comment by sarambl** [comment]
Check here https://nordicesmhub.github.io/NEGI-Abisko-2019/training/CMIP6_data.html
