### ISSUE TITLE
Hiking map and tours around you

### ISSUE THREAD

**Issue by franzihe** [NordicESMhub/NEGI-Abisko-2019#73]
Useful app incl. map to check for hikes around your location.
AllTrails - no login required:  https://www.alltrails.com/mobile

**Comment by aidenrobert** [comment]
Is anybody into the idea of going on a hike? I'm down

**Comment by marikoll** [comment]
This is an app that contains the trails and topographic maps in the area around here:

BackwaterMaps

God tur!

**Comment by pzieger** [comment]
Please don't forget to sign out and in if you are going on a hike tomorrow! The list will be right at the reception on the whiteboard. Thanks!

**Comment by franzihe** [comment]
@tuulivarenka @JohanRaniseth @sigridjb @jrieksta @aidenrobert  are up for a hike to/in the direction of Lapporten? It is appr. 10km to the gate.

**Comment by sigridjb** [comment]
Yes @franzihe ! Either that or Kongsvegen, in the national park, also approx 10k per way is we want to go all the way.

**Comment by JohanRaniseth** [comment]
Me, @lassekva @bjorngli @marekrataj is thinking about going Kongsvegen.

**Comment by franzihe** [comment]
Cool. Let's discuss during breakfast. Sunset is at 16:50 :p
