### ISSUE TITLE
Installing pysplit package in JupiterHub

### ISSUE THREAD

**Issue by ksenia-tabakova** [NordicESMhub/NEGI-Abisko-2019#74]
Hi! Is it possible to make it working at JupiterHub [https://github.com/mscross/pysplit]?

**Comment by annefou** [comment]
Sure. It takes a bit of time to re-create the jupyterhub image. If you need it now, let's install it in your environment,

**Comment by daliagachc** [comment]
shall we close this issue? 
@ksenia-tabakova: 
you can run this in your jupyterhub terminla:
```bash
pip install --user pysplit
```
