### ISSUE TITLE
I can't get in to the aerocom-user-database?

### ISSUE THREAD

**Issue by sarambl** [NordicESMhub/NEGI-Abisko-2019#95]
@jgliss @MichaelSchulzMETNO Do you know why? I got in yesterday fine :cry: :disappointed: :sob: 
I would be very happy if you have any idea why! :grinning: :tada: :+1: :1st_place_medal:

**Comment by jgliss** [comment]
@sarambl I also can't get in at the moment.

**Comment by MichaelSchulzMETNO** [comment]
The server is probably down, I need to ask Jan and help desk, 

Michael

**Comment by sarambl** [comment]
I see, thanks! I close this then
