### ISSUE TITLE
I want to install a package and I get error related to inconsistency.

### ISSUE THREAD

**Issue by jrieksta** [NordicESMhub/NEGI-Abisko-2019#98]
**The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:**

![image](https://user-images.githubusercontent.com/36596426/67165007-8ab51f00-f380-11e9-9d45-d672ff0555d4.png)

![image](https://user-images.githubusercontent.com/36596426/67165010-93a5f080-f380-11e9-97da-5d95da3af0f5.png)

The initial package I want is ggplot2, and I followed steps mentioned here : https://towardsdatascience.com/how-to-use-ggplot2-in-python-74ab8adec129

by installing **plotnine** (and the error messages appear when I try to install it)

Do you have any comments on this?
Thanks,
Jolanta

**Comment by JohanRaniseth** [comment]
You could try:
conda update --all 

And then do the ggplot2 installation. If that doesnt work maybe there are other commands/comments here that might help. https://stackoverflow.com/questions/55527354/the-environment-is-inconsistent-please-check-the-package-plan-carefully

**Comment by annefou** [comment]
@jrieksta you don't get an error related to inconsistency. It is related to permissions (you do not have write access). I added plotnine but it will take about one hour to build. 
If you wish to install local packages, you can you pip (it does not check for package inconsistency):

```
pip install plotnine --user
```

**Comment by annefou** [comment]
@jrieksta plotline is now available so I close the issue.
