### ISSUE TITLE
Updated schedule in private-repository!

### ISSUE THREAD

**Issue by johtoblan** [NordicESMhub/NEGI-Abisko-2019#99]
The updated schedule linked on [https://nordicesmhub.github.io/NEGI-Abisko-2019/intro ](https://nordicesmhub.github.io/NEGI-Abisko-2019/intro) links to the private repository.

It can be found on the [ACES page](https://www.aces.su.se/aces/wp-content/uploads/2019/05/Abisko-course-schedule-short-20191019.pdf).

So are we to have access to the private or will the schedule be put on the public one?

**Comment by johtoblan** [comment]
@annefou @pzieger

**Comment by annefou** [comment]
@johtoblan From the private repo. It is also linked from the main Abisko website https://nordicesmhub.github.io/NEGI-Abisko-2019/intro (Detailed programme).

**Comment by johtoblan** [comment]
I am getting a 404 when accessing the priavte-repo

**Comment by annefou** [comment]
@johtoblan You should have access to the private repo. Did you login to github?

**Comment by annefou** [comment]
@johtoblan oups. sorry. my fault! I did not add the student team to the repo! It should work now!!!

**Comment by johtoblan** [comment]
@annefou Yes, Thanks!
